/// `flowbrain init` command — generates a flowbrain.yaml template.
library;

import 'dart:io';

import 'package:args/args.dart';
import 'package:logging/logging.dart';

final _log = Logger('flowbrain.core.boot.commands.init');

/// Handles the `flowbrain init` CLI command.
class InitCommand {
  /// Build the [ArgParser] for the init subcommand.
  static ArgParser parser() {
    return ArgParser()
      ..addOption('profile',
          allowed: ['server', 'standard'],
          defaultsTo: 'standard',
          help: 'Configuration profile template')
      ..addFlag('force',
          negatable: false,
          help: 'Overwrite existing flowbrain.yaml')
      ..addOption('output',
          defaultsTo: './flowbrain.yaml', help: 'Output file path');
  }

  /// Execute the init command.
  static Future<int> run(ArgResults args) async {
    final profile = args['profile'] as String;
    final force = args['force'] as bool;
    final outputPath = args['output'] as String;

    final file = File(outputPath);

    if (file.existsSync() && !force) {
      _log.severe(
          'File already exists: $outputPath. Use --force to overwrite.');
      return 1;
    }

    final template = _generateTemplate(profile);
    file.writeAsStringSync(template);
    _log.info('Created $outputPath with "$profile" profile.');
    return 0;
  }

  /// Generate a YAML template for the given profile.
  static String _generateTemplate(String profile) {
    final buf = StringBuffer();
    buf.writeln('# FlowBrain configuration — $profile profile');
    buf.writeln('# Generated by `flowbrain init --profile=$profile`');
    buf.writeln();
    buf.writeln('version: 1');
    buf.writeln();
    buf.writeln('profile: $profile');
    buf.writeln();
    buf.writeln('providers:');
    buf.writeln('  llm:');
    buf.writeln('    driver: openai');
    buf.writeln('    model: gpt-4');
    buf.writeln('    # api_key: \${OPENAI_API_KEY}');
    buf.writeln();
    buf.writeln('storage:');
    buf.writeln('  driver: sqlite');
    buf.writeln('  path: ./data/flowbrain.db');
    buf.writeln();

    if (profile == 'server') {
      buf.writeln('mcp:');
      buf.writeln('  server:');
      buf.writeln('    transport: stdio');
      buf.writeln('    # port: 3000');
      buf.writeln();
    }

    buf.writeln('knowledge:');
    buf.writeln('  auto_digest: true');
    buf.writeln('  digest_interval: 3600');
    buf.writeln();
    buf.writeln('# packs: []');

    return buf.toString();
  }
}
